#!/bin/env python3
from androidtools.apkdump import parsing

# Main entry point for dexdump, used to dump test information extracted form the dex files within an Android apk

if __name__ == "__main__":
    parsing.main()
